apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-helloworld
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/ellery/hello-nginx:v0.6
        ports:
        - containerPort: 80
        securityContext:
          runAsGroup: 0
          runAsUser: 0

