apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-helloworld
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/jacky_lee_eds/nginx:1.27.4
        ports:
        - containerPort: 80
#        securityContext:
#          runAsGroup: 101
#          runAsUser: 101

