apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-helloworld
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/jacky_lee_eds/nginx:1.27.4  # 使用 unprivileged 版本
        ports:
        - containerPort: 8080  # 改為 8080
        args: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]  # 指定 Nginx 配置
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /etc/nginx/nginx.conf  # 掛載 ConfigMap 配置
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-config  # 掛載 ConfigMap 來修改 Nginx 監聽的 Port
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-helloworld
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen 8080;  # 監聽 8080
            server_name localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        }
    }
