apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-helloworld
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30001 
  type: NodePort
